name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: raven-actions/actionlint@v2
